version: "3.1"

services:
  db:
    image: postgres:alpine
    container_name: django-simplest
    privileged: true
    ports:
      - 25432:5432
    hostname: 127.0.0.1
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1

  backend:
    build: ./backend
    privileged: true
    ports:
      - 8080:8080
    command: bash -c "
        python manage.py migrate && 
        gunicorn backend.wsgi -b 0.0.0.0:8080
        "
    depends_on:
      - db










